"""In-memory session/piece-tree store for the interactive split UI.

A Session holds every piece ever produced by cutting, as a tree: the
originally-uploaded (scaled) mesh is the root; cutting a leaf piece replaces
it with its children in `leaves` but keeps the piece itself in `pieces` (as
an internal/non-leaf node) so the tree can be inspected or undone. Only
`leaves` are eligible to be cut further or included in the final
connector/export pass (see `connectors.add_connectors_after_cuts`, which
already knows how to place connectors across an arbitrary multi-level cut
tree given the full list of `ResolvedCut`s applied anywhere in it).
"""
from __future__ import annotations

import math
import threading
import time
import uuid
from dataclasses import dataclass, field

import numpy as np
import trimesh

from .cutting import cut_mesh
from .geometry import Cut, ResolvedCut, axis_index, resolve_cuts
from .progress import ProgressReporter

_SESSION_TTL_SECONDS = 30 * 60  # idle sessions are swept after this long


@dataclass
class PieceNode:
    id: str
    mesh: trimesh.Trimesh
    parent_id: str | None
    # The cut-group that produced this piece as a child (None for the root).
    # Every child produced by the same cut_piece() call shares one
    # cut_group_id, so undo_cut can remove exactly (and only) that
    # operation's effects.
    cut_group_id: str | None
    children_ids: list[str] = field(default_factory=list)
    # Net rigid transform applied by rotate_piece/align_piece_to_cut since
    # this node was created (identity if never reoriented). `mesh` is always
    # the literal, current, user-facing geometry -- `mesh` transformed by
    # this matrix's inverse recovers the piece exactly as it looked right
    # after the cut that created it, which is the ONLY frame in which
    # `session.applied_cuts`' recorded (origin, normal) planes still
    # describe this piece's actual cut faces. Reset implicitly on every new
    # PieceNode (cutting always starts a fresh piece at identity, since its
    # own cut just became its new canonical reference frame) -- this field
    # exists precisely because rotating a LEAF (the only thing rotate_piece
    # ever touches) reorients it independently of whatever un-rotated
    # sibling it still needs to face across their shared interface; without
    # tracking this, connector placement silently finds nothing there (see
    # web.py's finish_session, which is the only place this gets consumed).
    display_rotation: "np.ndarray" = field(default_factory=lambda: np.eye(4))


@dataclass
class CutGroup:
    id: str
    piece_id: str  # the piece that was cut to produce this group's children
    child_ids: list[str]
    resolved_cuts: list[ResolvedCut]  # removed from Session.applied_cuts on undo


@dataclass
class Session:
    id: str
    filename: str
    scale_factor: float
    pieces: dict[str, PieceNode] = field(default_factory=dict)
    leaves: set[str] = field(default_factory=set)
    cut_groups: dict[str, CutGroup] = field(default_factory=dict)
    applied_cuts: list[ResolvedCut] = field(default_factory=list)
    last_activity: float = field(default_factory=time.time)
    lock: threading.Lock = field(default_factory=threading.Lock)
    # The exact scale/hollow parameters `web.py`'s create_session_endpoint
    # used to build the root piece from the raw uploaded file -- stored here
    # (rather than just the resolved `scale_factor`) so `export_session`/
    # `replay_history` can reproduce byte-for-byte identical starting
    # geometry from a re-uploaded copy of the same original file, including
    # hollowing (which isn't otherwise recoverable once baked into the root
    # mesh). Set once at session creation, never mutated after.
    create_params: dict = field(default_factory=dict)
    # Ordered, JSON-serializable log of every cut/rotate/align/undo call
    # made against this session, each carrying enough to replay it exactly
    # (see replay_history) -- this plus create_params is the entire
    # persistable state of a session; meshes themselves are never stored
    # here (regenerated by replay) since they're the expensive part this
    # mechanism exists to avoid persisting.
    history: list[dict] = field(default_factory=list)

    def touch(self) -> None:
        self.last_activity = time.time()


_SESSIONS: dict[str, Session] = {}
_SESSIONS_LOCK = threading.Lock()


def create_session(
    mesh: trimesh.Trimesh, filename: str, scale_factor: float, create_params: dict | None = None
) -> Session:
    session_id = uuid.uuid4().hex
    root = PieceNode(id="root", mesh=mesh, parent_id=None, cut_group_id=None)
    session = Session(id=session_id, filename=filename, scale_factor=scale_factor, create_params=create_params or {})
    session.pieces["root"] = root
    session.leaves.add("root")
    with _SESSIONS_LOCK:
        _SESSIONS[session_id] = session
    return session


def get_session(session_id: str) -> Session | None:
    with _SESSIONS_LOCK:
        session = _SESSIONS.get(session_id)
    if session is not None:
        session.touch()
    return session


def close_session(session_id: str) -> None:
    with _SESSIONS_LOCK:
        _SESSIONS.pop(session_id, None)


def sweep_expired_sessions(now: float | None = None) -> int:
    """Remove sessions idle longer than _SESSION_TTL_SECONDS. Returns the
    count removed. Call this periodically (see web.py's background sweep) —
    full meshes live in server memory for the session's lifetime, so
    unbounded sessions is a real memory leak, not a theoretical one."""
    now = now if now is not None else time.time()
    with _SESSIONS_LOCK:
        expired = [sid for sid, s in _SESSIONS.items() if now - s.last_activity > _SESSION_TTL_SECONDS]
        for sid in expired:
            del _SESSIONS[sid]
    return len(expired)


def cut_piece(
    session: Session,
    piece_id: str,
    axis: str,
    cuts: list["Cut | float"],
    progress: ProgressReporter | None = None,
    allow_floating_regions: bool = False,
) -> list[PieceNode]:
    """Cut the leaf piece `piece_id` along `axis` at `cuts`, replacing it with
    its children in `session.leaves`. Raises KeyError if `piece_id` isn't a
    current leaf (stale client state — e.g. it was already cut or undone by
    another request), CutPlacementError if the cut itself fails (same as the
    existing single-shot pipeline — surface this to the caller unchanged)."""
    if piece_id not in session.leaves:
        raise KeyError(f"'{piece_id}' is not a current leaf piece")
    node = session.pieces[piece_id]
    resolved = resolve_cuts(node.mesh, axis, cuts)
    sub_pieces = cut_mesh(node.mesh, resolved, progress=progress, allow_floating_regions=allow_floating_regions)

    group_id = uuid.uuid4().hex
    child_nodes = []
    for sub in sub_pieces:
        child_id = uuid.uuid4().hex
        child = PieceNode(id=child_id, mesh=sub, parent_id=piece_id, cut_group_id=group_id)
        session.pieces[child_id] = child
        node.children_ids.append(child_id)
        child_nodes.append(child)

    session.cut_groups[group_id] = CutGroup(
        id=group_id, piece_id=piece_id, child_ids=[c.id for c in child_nodes], resolved_cuts=resolved
    )
    session.leaves.discard(piece_id)
    session.leaves.update(c.id for c in child_nodes)
    session.applied_cuts.extend(resolved)
    session.history.append({
        "op": "cut",
        "parent_id": piece_id,
        "axis": axis,
        "cuts": [_serialize_cut(c) for c in cuts],
        "allow_floating_regions": allow_floating_regions,
        "child_ids": [c.id for c in child_nodes],
    })
    session.touch()
    return child_nodes


def _serialize_cut(cut: "Cut | float") -> dict:
    c = Cut.coerce(cut)
    return {"position": c.position, "tilt_a": c.tilt_a, "tilt_b": c.tilt_b}


def rotate_piece(session: Session, piece_id: str, axis: str, degrees: float) -> PieceNode:
    """Rotate the leaf piece `piece_id` by `degrees` around `axis`, in
    place — mutates its mesh but not the tree structure (same piece_id, same
    node, just reoriented), so it doesn't touch `applied_cuts`/`cut_groups`
    at all. Only ever offered for pieces with no children yet: rotating a
    piece that's already been cut further would leave its (already-fixed)
    children's geometry out of sync with the parent's new orientation, and
    there's no sane way to "rotate the cut tree below it" after the fact.
    Pivots around the piece's own bounding-box center, so the piece stays
    roughly where it was in the viewer rather than swinging off to wherever
    the origin happens to be. Also accumulates into `node.display_rotation`
    (see PieceNode) so connector placement at finish time can still find
    this piece's cut faces despite the reorientation. Raises KeyError if
    `piece_id` isn't a current leaf."""
    if piece_id not in session.leaves:
        raise KeyError(f"'{piece_id}' is not a current leaf piece")
    node = session.pieces[piece_id]
    axis_vec = [0.0, 0.0, 0.0]
    axis_vec[axis_index(axis)] = 1.0
    center = (node.mesh.bounds[0] + node.mesh.bounds[1]) / 2.0
    transform = trimesh.transformations.rotation_matrix(math.radians(degrees), axis_vec, point=center)
    rotated = node.mesh.copy()
    rotated.apply_transform(transform)
    node.mesh = rotated
    node.display_rotation = transform @ node.display_rotation
    session.history.append({"op": "rotate", "piece_id": piece_id, "axis": axis, "degrees": degrees})
    session.touch()
    return node


def _rotation_aligning_vector_to_nearest_axis(v: np.ndarray) -> np.ndarray | None:
    """Return the rotation matrix that rotates unit vector `v` onto whichever
    world axis it's closest to (preserving sign — e.g. a normal mostly
    pointing at -Y snaps to -Y, not +Y), or None if `v` is already aligned
    (within floating-point noise) so callers can skip a no-op transform."""
    dominant = int(np.argmax(np.abs(v)))
    target = np.zeros(3)
    target[dominant] = 1.0 if v[dominant] >= 0 else -1.0

    if np.allclose(v, target, atol=1e-9):
        return None

    # Standard vector-to-vector rotation (Rodrigues' formula) via the axis
    # perpendicular to both and the angle between them.
    axis = np.cross(v, target)
    axis_norm = np.linalg.norm(axis)
    if axis_norm < 1e-12:
        # v and target are anti-parallel (180 degrees apart) -- cross product
        # is degenerate, so pick any axis perpendicular to v to rotate around.
        perp = np.array([1.0, 0.0, 0.0]) if abs(v[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
        axis = np.cross(v, perp)
        axis_norm = np.linalg.norm(axis)
    axis = axis / axis_norm
    angle = math.acos(float(np.clip(np.dot(v, target), -1.0, 1.0)))
    return trimesh.transformations.rotation_matrix(angle, axis)


def align_piece_to_cut(session: Session, piece_id: str) -> PieceNode:
    """Rotate leaf piece `piece_id` so the cut face that produced it snaps to
    its nearest world axis -- meant for pieces created by a tilted cut
    (nonzero tilt_a/tilt_b), whose bounding box otherwise reports an inflated,
    misleading footprint (the AABB of a diagonal face padded out along every
    axis) instead of the piece's true, tightest-fit size. A no-op (returns
    the piece unchanged) for the root piece or a piece produced by a plain
    axis-aligned cut, since there's nothing to align. If the cut that
    produced this piece involved more than one plane (a multi-plane cut in
    one call, e.g. cutting into 3+ pieces at once) with different tilts on
    each side, aligns to whichever of this piece's cut faces is furthest from
    axis-aligned -- that's the one dominating the bounding-box inflation.
    Also accumulates into `node.display_rotation` (see PieceNode) so
    connector placement at finish time can still find this piece's cut
    faces despite the reorientation. Raises KeyError if `piece_id` isn't a
    current leaf."""
    if piece_id not in session.leaves:
        raise KeyError(f"'{piece_id}' is not a current leaf piece")
    node = session.pieces[piece_id]
    if node.cut_group_id is None:
        return node  # root piece: never produced by a cut

    group = session.cut_groups[node.cut_group_id]
    # "Furthest from axis-aligned" = smallest max-abs-component (a
    # perfectly axis-aligned normal has one component at 1.0; a 45-degree
    # tilt brings that down toward ~0.71).
    worst_cut = min(group.resolved_cuts, key=lambda c: float(np.max(np.abs(c.normal))))
    transform = _rotation_aligning_vector_to_nearest_axis(worst_cut.normal)
    if transform is None:
        return node  # already axis-aligned; nothing to do

    center = (node.mesh.bounds[0] + node.mesh.bounds[1]) / 2.0
    # rotation_matrix() above was built with no pivot (rotates about the
    # origin) -- re-derive it with the piece's own center as pivot, same
    # convention as rotate_piece, so the piece doesn't swing away from where
    # it sits in the viewer.
    angle, direction, _point = trimesh.transformations.rotation_from_matrix(transform)
    pivoted = trimesh.transformations.rotation_matrix(angle, direction, point=center)

    rotated = node.mesh.copy()
    rotated.apply_transform(pivoted)
    node.mesh = rotated
    node.display_rotation = pivoted @ node.display_rotation
    session.history.append({"op": "align", "piece_id": piece_id})
    session.touch()
    return node


def undo_cut(session: Session, piece_id: str, _record_history: bool = True) -> None:
    """Undo the cut that produced `piece_id`'s children: remove the children
    (and, recursively, anything cut from them — a piece can't be un-cut while
    its own children still exist, so this cascades down first), restore
    `piece_id` as a leaf, and remove that cut's ResolvedCuts from
    session.applied_cuts. Raises KeyError if `piece_id` has no children (never
    cut, or already undone). `_record_history` is internal -- only the
    top-level call (not its recursive cascade) is recorded, since replaying
    that one recorded entry already re-triggers the same cascade."""
    node = session.pieces[piece_id]
    if not node.children_ids:
        raise KeyError(f"'{piece_id}' has no cut to undo")

    # Cascade: recursively undo any grandchildren first (a child that was
    # itself cut further must be un-cut before it can be removed).
    for child_id in list(node.children_ids):
        child = session.pieces.get(child_id)
        if child and child.children_ids:
            undo_cut(session, child_id, _record_history=False)

    group_id = session.pieces[node.children_ids[0]].cut_group_id
    group = session.cut_groups.pop(group_id)
    for child_id in group.child_ids:
        session.pieces.pop(child_id, None)
        session.leaves.discard(child_id)
    node.children_ids.clear()
    session.leaves.add(piece_id)

    # Remove exactly this group's ResolvedCuts (by identity, not equality —
    # ResolvedCut isn't safe/meaningful to dedupe by value here) from
    # applied_cuts.
    removed_ids = {id(c) for c in group.resolved_cuts}
    session.applied_cuts = [c for c in session.applied_cuts if id(c) not in removed_ids]
    if _record_history:
        session.history.append({"op": "undo", "piece_id": piece_id})
    session.touch()


def replay_history(session: Session, history: list[dict]) -> list[str]:
    """Re-run every cut/rotate/align/undo operation in `history` (as
    recorded by cut_piece/rotate_piece/align_piece_to_cut/undo_cut, in
    order) against a freshly-created `session` whose root is the exact same
    starting mesh (see `Session.create_params` -- the caller is responsible
    for reproducing that starting mesh, e.g. by re-running the same
    scale/hollow steps against a re-uploaded copy of the original file).

    Piece ids are randomly generated fresh each time a cut happens (see
    cut_piece), so a naive replay can't reuse the OLD ids a recorded entry
    refers to -- `id_map` tracks old-id -> newly-generated-id as replay
    proceeds, seeded with the one id that's always stable ("root"), and
    every entry's piece/parent id is translated through it before use.

    Returns the (new-id) chronological cut order -- the same thing the
    frontend's `tree.cutOrder` tracks live during normal use (see
    interactiveState.js) -- so a resumed session's "Undo last cut" has a
    correct history to work from immediately, not just after the user's
    next real cut."""
    id_map = {"root": "root"}
    cut_order: list[str] = []
    for entry in history:
        op = entry["op"]
        if op == "cut":
            parent_id = id_map[entry["parent_id"]]
            cuts = [Cut(**c) for c in entry["cuts"]]
            children = cut_piece(
                session, parent_id, entry["axis"], cuts,
                allow_floating_regions=entry.get("allow_floating_regions", False),
            )
            for old_id, node in zip(entry["child_ids"], children):
                id_map[old_id] = node.id
            cut_order.append(parent_id)
        elif op == "rotate":
            rotate_piece(session, id_map[entry["piece_id"]], entry["axis"], entry["degrees"])
        elif op == "align":
            # A piece_id absent from id_map means it was produced by a cut
            # that was later undone earlier in this same history -- nothing
            # to align, and no later entry can reference it either (a fresh
            # id would be minted if that branch were ever re-cut), so this
            # is unreachable for a genuinely-recorded history, not a bug
            # this needs to tolerate; skip defensively rather than crash a
            # resume over a hypothetical malformed/hand-edited file.
            mapped = id_map.get(entry["piece_id"])
            if mapped is not None:
                align_piece_to_cut(session, mapped)
        elif op == "undo":
            undone_id = id_map[entry["piece_id"]]
            undo_cut(session, undone_id)
            # Drop the entry for the cut just undone, plus every entry whose
            # parent no longer exists at all (the cascade in undo_cut
            # deletes any piece that was itself cut further beneath the
            # undone one) -- mirrors the frontend's pruneSubtree-based
            # filtering in interactiveState.js, just keyed off session state
            # directly instead of walking the tree by hand a second time.
            cut_order = [pid for pid in cut_order if pid != undone_id and pid in session.pieces]
    return cut_order


def tree_summary(session: Session) -> dict:
    """JSON-serializable snapshot of the whole tree, for GET /sessions/{id}
    (reconstructing UI state after a page refresh) — piece meshes themselves
    are NOT included here (too large); the piece-preview endpoint fetches an
    individual piece's STL bytes on demand."""
    return {
        "session_id": session.id,
        "leaves": sorted(session.leaves),
        "pieces": {
            pid: {
                "parent_id": node.parent_id,
                "children_ids": node.children_ids,
                "is_leaf": pid in session.leaves,
                "extents": node.mesh.extents.tolist(),
                "volume": float(node.mesh.volume),
                "bounds": node.mesh.bounds.tolist(),
            }
            for pid, node in session.pieces.items()
        },
    }
